export type Product = {
  id: string;
  name: string;
  category: string;
  categorySlug: string;
  description: string;
  specs: string[];
  applications: string[];
  image: string; // Replace with your own photo when available
};

export const products: Product[] = [
  // ── NETS ────────────────────────────────────────────────────────────────
  {
    id: "cargo-net",
    name: "Cargo Net",
    category: "Nets",
    categorySlug: "nets",
    description: "Heavy-duty cargo nets manufactured to specification for safe lifting and securing of goods on marine vessels and offshore platforms.",
    specs: ["Custom sizes available", "Polypropylene or nylon construction", "Rated load capacity on request", "With or without stiffeners"],
    applications: ["Offshore platform cargo transfer", "Ship deck cargo securing", "Oil & gas logistics"],
    image: "https://res.cloudinary.com/dmzhovcc/image/upload/f_auto,q_auto/cargo_net",
  },
  {
    id: "scramble-net",
    name: "Scramble Net",
    category: "Nets",
    categorySlug: "nets",
    description: "Certified scramble nets for personnel evacuation and boarding operations on marine vessels.",
    specs: ["SOLAS compliant available", "Manila or synthetic rope", "Custom dimensions", "UV resistant"],
    applications: ["Marine evacuation", "Vessel boarding", "Safety drills"],
    image: "/scramble.jpg",
  },
  {
    id: "gangway-net",
    name: "Gangway Net",
    category: "Nets",
    categorySlug: "nets",
    description: "Gangway safety nets installed beneath walkways to protect personnel from falls during boarding and disembarkation.",
    specs: ["Custom length and width", "High-tensile polyester", "Safety net standard compliant", "Quick-deploy rigging"],
    applications: ["Vessel gangway safety", "Offshore platform access", "Port operations"],
    image: "https://res.cloudinary.com/dmzhovcc/image/upload/v1788362042/gangway_net.jpg",
  },
  {
    id: "steel-wire-rope-net",
    name: "Steel Wire Rope Net",
    category: "Nets",
    categorySlug: "nets",
    description: "Industrial-grade steel wire rope nets for heavy-load containment, debris protection, and structural safety.",
    specs: ["Galvanised or stainless steel", "Various mesh sizes", "Corrosion resistant coating", "Rated to specification"],
    applications: ["Heavy cargo containment", "Debris netting", "Structural protection"],
    image: "/steel_wire_rope_net.jpg",
  },
  // ── ROPES & SLINGS ──────────────────────────────────────────────────────
  {
    id: "wire-rope",
    name: "Wire Rope & Fittings",
    category: "Ropes & Slings",
    categorySlug: "ropes",
    description: "High-tensile wire ropes with a full range of fittings — sockets, shackles, grips, thimbles and more — for marine and industrial lifting.",
    specs: ["Various grades and constructions", "Sockets, shackles, grips supplied", "Galvanised or ungalvanised", "Tested and certified"],
    applications: ["Lifting operations", "Marine rigging", "Offshore mooring"],
    image: "https://images.pexels.com/photos/4483610/pexels-photo-4483610.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: "slings",
    name: "Slings Fabrication & Management",
    category: "Ropes & Slings",
    categorySlug: "ropes",
    description: "Custom sling fabrication, testing, certification, and ongoing management for offshore and onshore lifting operations.",
    specs: ["Wire rope and synthetic slings", "Load tested and certified", "Colour-coded to industry standard", "Full traceability documentation"],
    applications: ["Offshore crane operations", "Heavy lift rigging", "Load securing"],
    image: "https://res.cloudinary.com/dmzhovcc/image/upload/v1788361297/webbing_sling.jpg",
  },
  {
    id: "rope-dressing",
    name: "Wire Hooks",
    category: "Ropes & Slings",
    categorySlug: "ropes",
    description: "Professional rope dressing and preservation service to extend the working life of wire and fibre ropes in marine environments.",
    specs: ["Suitable for wire and fibre rope", "Marine-grade lubricants", "Prevents corrosion and wear", "On-site service available"],
    applications: ["Wire rope maintenance", "Offshore rigging preservation", "Mooring line upkeep"],
    image: "/wire_hooks.jpg",
  },

    {
    id: "lifting-gear-supply",
    name: "Lifting Gear Supply",
    category: "Ropes & Slings",
    categorySlug: "ropes",
    description: "Supply of certified lifting gear and rigging hardware — shackles, hooks, chains, and fittings — for offshore and onshore lifting operations.",
    specs: ["Certified to industry standard", "Full range of load capacities", "Available for hire or purchase", "Full documentation supplied"],
    applications: ["Offshore lifting operations", "Rigging and load handling", "Crane and hoist support"],
    image: "/lifting_gear.jpg",
  },
  // ── LADDERS & ACCESS ────────────────────────────────────────────────────
  {
    id: "pilot-ladder",
    name: "Pilot Ladder",
    category: "Ladders & Access",
    categorySlug: "ladders",
    description: "SOLAS-compliant pilot ladders for safe pilot boarding and disembarkation from vessels.",
    specs: ["SOLAS Chapter V / LSA Code compliant", "Hardwood treads", "Manila or synthetic side ropes", "Tested to 750kg minimum"],
    applications: ["Pilot boarding", "Vessel inspections", "Port authority access"],
    image: "https://res.cloudinary.com/dmzhovcc/image/upload/v1788361274/pilot_ladder.jpg",
  },
  {
    id: "jacobs-ladder",
    name: "Jacob's Ladder",
    category: "Ladders & Access",
    categorySlug: "ladders",
    description: "Traditional Jacob's ladders for vessel boarding and personnel access in marine and offshore operations.",
    specs: ["Hardwood or aluminium rungs", "Natural or synthetic rope sides", "Custom lengths", "Lightweight and compact"],
    applications: ["Personnel boarding", "Offshore access", "Ship-to-ship transfer"],
    image: "https://res.cloudinary.com/dmzhovcc/image/upload/v1788361277/jacobs_ladder.jpg",
  },
  {
    id: "lifeboat-boarding-ladder",
    name: "Lifeboat Boarding Ladder",
    category: "Ladders & Access",
    categorySlug: "ladders",
    description: "Marine lifeboat and rescue boat boarding ladders built to SOLAS specifications for emergency use.",
    specs: ["SOLAS compliant", "Non-slip treads", "Corrosion-resistant fittings", "Lengths to specification"],
    applications: ["Lifeboat stations", "Rescue boat deployment", "Emergency evacuation"],
    image: "/lifeboat_ladder.jpeg",
  },
  // ── SAFETY & RESCUE ─────────────────────────────────────────────────────
  {
    id: "rescue-line",
    name: "Rescue Line",
    category: "Safety & Rescue",
    categorySlug: "safety",
    description: "High-visibility rescue throwing lines for man-overboard recovery and personnel rescue in marine environments.",
    specs: ["Minimum 30m length", "High-visibility colour", "Buoyant line", "Quick-deploy bag or reel"],
    applications: ["Man overboard recovery", "Rescue operations", "Vessel safety equipment"],
    image: "/rescue_line.jpeg",
  },
  {
    id: "single-stretcher",
    name: "Single Stretcher",
    category: "Safety & Rescue",
    categorySlug: "safety",
    description: "Lightweight single-person stretcher for casualty evacuation in marine and offshore environments.",
    specs: ["Aluminium alloy frame", "Load rated to 150kg", "Foldable for compact storage", "Carry handles both sides"],
    applications: ["Offshore medical evacuation", "Vessel first response", "Emergency rescue"],
    image: "https://res.cloudinary.com/dmzhovcc/image/upload/v1788361274/single_stretcher.jpg",
  },
  {
    id: "double-stretcher",
    name: "Double Stretcher",
    category: "Safety & Rescue",
    categorySlug: "safety",
    description: "Heavy-duty double stretcher for two-casualty evacuation or bariatric patient handling offshore.",
    specs: ["Reinforced aluminium frame", "Load rated to 300kg", "Adjustable width", "Includes restraint straps"],
    applications: ["Multi-casualty response", "Offshore emergency", "Platform evacuation"],
    image: "/double_stretcher.jpeg",
  },
  // ── LIFTING GEAR ────────────────────────────────────────────────────────
  {
    id: "lifting-gear-examination",
    name: "Lifting Gear Examination",
    category: "Testing & Certification",
    categorySlug: "testing",
    description: "Thorough examination, testing, and certification of all lifting gear and equipment to regulatory and industry standards.",
    specs: ["Visual and NDT inspection", "Load testing where required", "Certified documentation issued", "LOLER/factory act compliant"],
    applications: ["Offshore lifting equipment", "Crane rigging certification", "Compliance audits"],
    image: "https://images.pexels.com/photos/1108101/pexels-photo-1108101.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: "testing-certification",
    name: "Testing & Certification",
    category: "Testing & Certification",
    categorySlug: "testing",
    description: "Full testing and certification services for wire ropes, slings, nets, and lifting accessories. Certificates issued with full traceability.",
    specs: ["Proof load testing", "Break load testing", "Third-party witnessing available", "Certificate with full traceability"],
    applications: ["Pre-use equipment certification", "Regulatory compliance", "Client documentation requirements"],
    image: "https://images.pexels.com/photos/3862132/pexels-photo-3862132.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  // ── BUOYS ───────────────────────────────────────────────────────────────
  {
    id: "cylindrical-buoy",
    name: "Cylindrical Buoy",
    category: "Buoys & Flotation",
    categorySlug: "buoys",
    description: "Heavy-duty cylindrical mooring and marker buoys for offshore and marine navigation.",
    specs: ["High-density polyethylene", "UV resistant outer shell", "Various diameters", "Stainless steel fittings"],
    applications: ["Mooring markers", "Channel marking", "Offshore navigation"],
    image: "https://images.pexels.com/photos/1001682/pexels-photo-1001682.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: "chain-through-buoy",
    name: "Chain Through Buoy",
    category: "Buoys & Flotation",
    categorySlug: "buoys",
    description: "Specialist chain-through mooring buoys designed for high-load mooring systems in offshore oil fields.",
    specs: ["Central chain passage tube", "High-strength HDPE", "Corrosion-resistant fittings", "Load rated to specification"],
    applications: ["Offshore mooring", "Single point mooring (SPM)", "Tanker berthing"],
    image: "/chain_through_buoy.jpeg",
  },
  {
    id: "pickup-buoy",
    name: "Pick-Up Buoy",
    category: "Buoys & Flotation",
    categorySlug: "buoys",
    description: "Bright-coloured pick-up buoys for marking mooring lines, anchor positions, and recovery lines.",
    specs: ["High-visibility colour", "Foam-filled unsinkable", "Rope attachment eye", "Lightweight"],
    applications: ["Mooring line marking", "Anchor marking", "Diver surface marking"],
    image: "pickup-buoy",
  },
  // ── SITE SERVICES ───────────────────────────────────────────────────────
  {
    id: "site-services",
    name: "Site Services",
    category: "Site Services",
    categorySlug: "site",
    description: "On-site rigging, rope management, inspection, and support services delivered directly to your offshore platform or onshore facility.",
    specs: ["Experienced riggers and inspectors", "Full PPE and safety compliance", "Short-notice mobilisation", "Comprehensive job reports"],
    applications: ["Offshore platform support", "Shutdown and turnaround", "Onshore industrial facilities"],
    image: "https://images.pexels.com/photos/2760243/pexels-photo-2760243.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
    {
    id: "crane-wire-installation",
    name: "Crane Wire Installation",
    category: "Site Services",
    categorySlug: "site",
    description: "Professional installation and replacement of crane wire rope, carried out by experienced riggers to manufacturer and safety specifications.",
    specs: ["Experienced rigging crew", "All crane types catered for", "Safety compliance checks included", "Short-notice mobilisation"],
    applications: ["Crane wire replacement", "Offshore platform cranes", "Onshore lifting equipment"],
    image: "https://res.cloudinary.com/dmzhovcc/image/upload/v1788362027/crane-wire.jpg",
  },
  {
    id: "instrumentation",
    name: "Instrumentation",
    category: "Site Services",
    categorySlug: "site",
    description: "Instrumentation services covering installation, calibration, and support for industrial monitoring and control equipment on site.",
    specs: ["Qualified technicians", "On-site and workshop service", "Calibration support", "Documented reporting"],
    applications: ["Offshore platform instrumentation", "Onshore facility support", "Industrial monitoring systems"],
    image: "https://res.cloudinary.com/dmzhovcc/image/upload/v1788362027/instrumentation.jpg",
  },
  {
    id: "rig-light-hire",
    name: "Rig Light Hire",
    category: "Site Services",
    categorySlug: "site",
    description: "Hire of rig lights and site lighting equipment for round-the-clock visibility on offshore platforms and onshore work sites.",
    specs: ["Weatherproof and rugged", "Various wattage options", "Mobile and fixed setups", "Delivery and setup available"],
    applications: ["Night operations lighting", "Platform and rig sites", "Onshore worksite lighting"],
    image: "https://res.cloudinary.com/dmzhovcc/image/upload/v1788362029/rig-light.jpg",
  },
  {
    id: "welding-machine-supply",
    name: "Welding Machine Supply",
    category: "Site Services",
    categorySlug: "site",
    description: "Supply and hire of welding machines and accessories for on-site fabrication, repair, and maintenance work.",
    specs: ["Diesel and electric options", "Regularly serviced equipment", "Delivery available", "Operator hire on request"],
    applications: ["On-site fabrication", "Structural repairs", "Maintenance and turnaround work"],
    image: "https://res.cloudinary.com/dmzhovcc/image/upload/v1788362028/welding-machine.jpg",
  },
  {
    id: "mobile-toilet-hire",
    name: "Mobile Toilet Hire",
    category: "Site Services",
    categorySlug: "site",
    description: "Hire of mobile toilet units for offshore and onshore sites, supporting welfare and hygiene requirements during operations.",
    specs: ["Self-contained units", "Regular servicing available", "Delivery and setup included", "Various unit sizes"],
    applications: ["Offshore platform welfare", "Onshore site facilities", "Shutdown and turnaround support"],
    image: "https://res.cloudinary.com/dmzhovcc/image/upload/v1788362027/mobile-toilet.jpg",
  },
  {
    id: "compressor-hire",
    name: "Compressor Hire",
    category: "Site Services",
    categorySlug: "site",
    description: "Hire of industrial air compressors for on-site pneumatic tools, cleaning, and general site operations.",
    specs: ["Diesel and electric units", "Various capacities available", "Delivery and collection", "Well-maintained fleet"],
    applications: ["Pneumatic tool operation", "Site cleaning and blow-down", "General industrial support"],
    image: "/compressor.jpeg",
  },
];

export const categories = [
  { slug: "nets",    label: "Nets",                  description: "Cargo, scramble, gangway, and steel wire rope nets to specification." },
  { slug: "ropes",   label: "Ropes & Slings",         description: "Wire ropes, sling fabrication, fittings, rope dressing, and lifting gear supply." },
  { slug: "ladders", label: "Ladders & Access",       description: "Pilot, Jacob's, and lifeboat boarding ladders for marine operations." },
  { slug: "safety",  label: "Safety & Rescue",        description: "Rescue lines, single and double stretchers for offshore emergency response." },
  { slug: "testing", label: "Testing & Certification",description: "Lifting gear examination, load testing, and certification services." },
  { slug: "buoys",   label: "Buoys & Flotation",      description: "Cylindrical, chain-through, and pick-up buoys for mooring and navigation." },
  { slug: "site",    label: "Site Services",          description: "On-site rigging, installation, and equipment hire — crane wire, instrumentation, welding machines, and site amenities." },
];
